### ISSUE TITLE
Home screen / Inbox

### ISSUE THREAD

**Issue by iuresti** [desarrolladorSLP/teckers-android-app#16]
As a user of the teckers app (any role) I want to see all the messages sent to me after login successfully into the application. 

Acceptance criteria:
1. Messages/Inbox will be the first screen after login (see image attached)
<img width="229" alt="inbox" src="https://user-images.githubusercontent.com/4889169/63403324-59ca6500-c3a4-11e9-80af-454f79642bb4.png">

2. Messages should be displayed in two lists (one high priority messages and one for low priority messages)
3. Each message in the list will be displayed with an image of the sender of the message, along with the subject and the date
4. If message hasn't been read it must be displayed in bold otherwise normal
5. An icon with a plus sign must be displayed in the bottom-right corner to add new emails 
6. An icon with a search sign must be displayed along with the plus icon to search for emails
7. The options in the menu must exist as they are displayed in the attached image

**Comment by ivanebernal** [comment]
Solved by #40
